### ISSUE TITLE
UXDI14 LAUREN SOLOMON resume

### ISSUE THREAD

**Issue by lsashleigh** [ga-dc/outcomes#100]
[Resume.pdf](https://github.com/ga-dc/outcomes/files/1611468/Resume.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. While I appreciate the eye-catching design of your resume, it doesn't do you many favors for your resume in terms of efficient use of space. There's a lot of content that ought to be included that can't be in this style. Be thoughtful about how to address this.

2. Include your brand statement at the top of your resume. It's a strong, confident way to introduce who you are and what you do.

3. "Immersive" is misspelled in your education section. (I'm a BYU grad, too!)

4. Add descriptions for UXDI and your previous work experience. Focus on what you accomplished in each position, and not just your responsibilities. Be specific!

5. Update your skills section to include the UX skills you're gaining. Move this section to the top.

Nice work! Let me know if you have questions.
A
