### ISSUE TITLE
david weisbarts resume UXDI14

### ISSUE THREAD

**Issue by dweisbart** [ga-dc/outcomes#101]
im a UX Professional with an in depth understanding of programming and user interfaces. i love to design and help make pleasing products for users. I thrive working in collaborative teams, great and conducting research.... i need help with my brand statement

[Davids revised Resume.pdf](https://github.com/ga-dc/outcomes/files/1612796/Davids.revised.Resume.pdf)

**Comment by allysonaustin** [comment]
Hi David,

I'm having a hard time opening this file. Can you resubmit?

A

**Comment by dweisbart** [comment]
Which file? Was it the resume?

**Comment by dweisbart** [comment]
[Davids revised Resume.pdf](https://github.com/ga-dc/outcomes/files/1632312/Davids.revised.Resume.pdf)
[Davids revised Resume.pdf](https://github.com/ga-dc/outcomes/files/1632313/Davids.revised.Resume.pdf)
did that work?
