### ISSUE TITLE
Shea Huening Resume [UXDi 14]

### ISSUE THREAD

**Issue by thesheaday** [ga-dc/outcomes#102]
"I am an avid and determined learner, tinkerer, and overall curious human. I love challenging myself both physically and mentally and I have a furious internal drive to constantly better myself."

[My_Resume_Designed(V2).pdf](https://github.com/ga-dc/outcomes/files/1613048/My_Resume_Designed.V2.pdf)

**Comment by allysonaustin** [comment]
See my comments on the draft-resume issue.

A
