### ISSUE TITLE
UXDI14 Megan McNeilly

### ISSUE THREAD

**Issue by mcneillymeg** [ga-dc/outcomes#106]
[MeganMcNeilly_Resume_UXDI.pdf](https://github.com/ga-dc/outcomes/files/1613319/MeganMcNeilly_Resume_UXDI.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! It was great to meet you this week. In addition to those things mentioned in our meeting, I have a few additional comments below.

1. No need to include your full address. City/state is sufficient.

2. Replace your summary of qualifications with a list of technical & UX skills.

3. Add UXDI to the top of your experience section. List your projects, and include the skills and technologies you used to complete them.

4. Your resume should be 1 page - pare down to meet that standard.

Great work! Let me know if you have questions.
A
