### ISSUE TITLE
UXDI Elliot Sonnenblick

### ISSUE THREAD

**Issue by elisonnen** [ga-dc/outcomes#114]
[resume updated.pdf](https://github.com/ga-dc/outcomes/files/1621008/resume.updated.pdf)
Revised resume..sorry 1st one was not at all ready..

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. Add UXDI to the top of your experience section. Include your projects, and list the skills and technologies you used to create each one.

2. Move your tools above your education section. 

3. Your brand statement packs a lot in just a little bit of space, but it's not always effective. It's reading more like a list of qualities than an explanation of who you are and what you do. I encourage you to read it out loud to help you identify the parts that need reworking. I'm happy to work with you during my office hours if you'd like.

4. Be careful with your colors. I encourage you to print out your resume to make sure this orange is dark enough to be readable.

Great work! Let me know if you have questions.
A
