### ISSUE TITLE
Jack Tyburski FINAL Materials

### ISSUE THREAD

**Issue by Simplejack17** [ga-dc/outcomes#116]
Resume-[Resume (3).pdf](https://github.com/ga-dc/outcomes/files/1644105/Resume.3.pdf)
GA Profile- https://profiles.generalassemb.ly/profiles/9946/steps/the_lead
Portfolio- http://jacks-portfolio.surge.sh/
LinkedIn- https://www.linkedin.com/in/jack-tyburski-083553145/

What types of roles/organizations are you interested in: Mainly marketing companies. Anything that does front end development

What are your top 3-5 technical skills: HTML/CSS, Javascript, React

How would you like us to pitch you? (Write 2 sentences in the third person): Jack is a hardworking personable web developer. He is always looking for opportunities to make other people happy.

What locations beyond D.C. are you job searching in?: Anything in the D.C. or NOVA area

**Comment by CoachJoyhaugen** [comment]
Hi Jack, 

Thank you for submitting your materials.  While I have so much empathy and sympathy for you and your family during this time, you have had quite some time with many reminders that your Outcomes materials needed to be complete.  We even met during class to strategize how to get caught up. 

As I look through your materials, they all need quite a bit of work. I am going to strongly encourage you to go back through the lessons for Outcomes Materials and refocus on your materials. 

[https://github.com/ga-dc/outcomes]

**Your Resume** 
GA should be under your experience section in addition to your education 
You can take off the label of Brand statement as that is a GA thing, not industry wide. 
Add your portfolio link (once it fully works) to your headline 
Add Washington D.C. to your headline 
Take off your hobbies and bulk up your skills 
bring data to your descriptions 

**Your LinkedIn**
None of your descriptions are filled out 
Your top 3 skills need to be developer skills 
Your summary should have your brand statement, not yoru career listing 
"A client driven junior web-developer, focused on strong communication, and strategic problem solving."

**Your GA Profile**
The top portion needs to be your brand statement 
GA should be up top 
You have several mis spellings in your personal questions and GA section 
When you say "low point" take out the part at GA

**Github**
Update your headshot to your GA Headshot 
Add your brand statement to your bio 

**Portfolio**
Needs to function

All of this being said, I am going to provide you with one final exception.  We will meet one on one tomorrow and go over your materials and I need all of them in top top 100% shape by Monday at 6PM.  This means that you have had someone else as well review your materials for spelling, grammar and making sure that everything works. I would encourage you to continue working between now and tomorrow on your materials so we can go through them again in our mtg tomorrow. 

Please let me know if you have any questions. 

Thanks! 
Joy

**Comment by Simplejack17** [comment]
You are correct. I understand that I had a lot of time and there is no excuse. I WILL have everything at 100% come Monday. Thank you for the review and suggestions on what I need to fix. I hope to have everything update to the best of my ability by tomorrow.
