### ISSUE TITLE
Brand Statement: #UXDI15

### ISSUE THREAD

**Issue by emcruer** [ga-dc/outcomes#125]
Hi, I'm Liza! I'm a UX Designer and I'm all about taking initiative in projects to get tasks done. I'm an engaging storyteller with an aptitude for creative solutions, collaborative work, planning and execution.

**Comment by samrijolie** [comment]
Hi, I'm Samri! I'm a UX Designer and a team player. My goal is to shine new light on your business and deliver solutions for growth and optimization via surprising insights, independent problem-solving, and great communication.

**Comment by samrijolie** [comment]
Hi, I'm Samri! I'm a UX Designer and a team player. My goal is to shine new light on your business and deliver solutions for growth and optimization via surprising insights, independent problem-solving, and great communication.

**Comment by Calderon00** [comment]
Javi is an engaging and natural leader who helps bridge teams and projects through communication, high energy and collaboration. He lives outside the box and is passionate about delivering creative and unique solutions. 

someone who takes initiative and collaborates well with others. He is an engaging communicator with an aptitude for creative solutions and skillfully executing her ideas.

**Comment by Calderon00** [comment]
Oops* cancel that last bit.

**Comment by allysonaustin** [comment]
@emcruer Thanks for submitting!

I love the message of your brand statement and you’ve chosen some really strong, specific action verbs to highlight - nice work!

Your statement ends on a strong note, but the first sentence lacks the momentum and finesse of the second. I encourage you to be a bit more specific - what kinds of projects and tasks do you take on?

Great work! Let me know if you have questions.
A
