### ISSUE TITLE
UXDI 15 Hunter Holmes Brand Statement 

### ISSUE THREAD

**Issue by ghost** [ga-dc/outcomes#126]
Hunter Holmes is Experienced in Enterprise Sales with a demonstrated history of working in the information technology and services industry. Skilled in Research, Event Planning, Fundraising, Customer Service, and Teamwork. Hunter is a strong creative who never turns down a challenge.

**Comment by allysonaustin** [comment]
Thanks for submitting!

Speak in first person. It comes across more confident and flows better on a resume/profile to talk as yourself, not about yourself.

Keep your format consistent - your second sentence isn’t actually a complete sentence. Also, it’s very distracting to a reader to have this much capitalization. Stick to the standard rules of capitalization to support readability.

What kinds of projects do you like to take on? How does this experience you’ve listed influence who you are - what is the effect? Be more specific to strengthen your statement.

Great work! Let me know if you have questions.
A
