### ISSUE TITLE
Javi Calderon: UXDI 15 Brand Statement

### ISSUE THREAD

**Issue by Calderon00** [ga-dc/outcomes#127]
Javi is an engaging and natural leader who helps bridge teams and projects through communication, high energy and collaboration. He lives outside the box and is passionate about delivering creative and unique solutions.

someone who takes initiative and collaborates well with others. He is an engaging communicator with an aptitude for creative solutions and skillfully executing her ideas.

**Comment by Calderon00** [comment]
Oops* cancel that last bit.

**Comment by allysonaustin** [comment]
Thanks for submitting!

Speak in first person. It comes across more confident and flows better on a resume/profile to talk as yourself, not about yourself.

The way you’ve used “bridge” in the first sentence is a bit unclear. What are you bringing together?
I encourage you to change “natural” to a more descriptive word. Consider the advantage of being a natural leader. Confident? Experienced? Decisive? These words are more specific and give a stronger effect.

Great work! Let me know if you have questions.
A
