### ISSUE TITLE
UXDI 15 Brand Statement Kristen Etzel

### ISSUE THREAD

**Issue by ketzel17** [ga-dc/outcomes#128]
Kristen is a UX Designer who is passionate about building creative solutions for clients.  She is a team player who provides fresh prospective and is always positive.

**Comment by allysonaustin** [comment]
Thanks for submitting!

You’ve made a good start and have chosen good qualities to highlight. However, your statement will benefit from more specific strong language and imagery. Solutions to what kinds of problems? What is your “fresh perspective?” Specificity will help you stand out from your peers and get at the characteristics that are unique to you.

Speak in first person. It comes across more confident and flows better on a resume/profile to talk as yourself, not about yourself.

You might also consider adding a section at the end to describe the ends of these characteristics. What is the effect of being a team player and being positive?

Great work! Let me know if you have questions.
A
