### ISSUE TITLE
UXDI15 Sayoh Mansaray: Draft Brand Statement

### ISSUE THREAD

**Issue by smansar** [ga-dc/outcomes#131]
An expressive storyteller with a knack for relating to a wide range of people, Sayoh is strongly driven by her imagination and ideals. Sayoh is inspired to create her UX Designer collage by pulling together her communications background, experience working with stakeholders, and her genuine delight in choosing the perfect words. A big thinker who views the world through a perceptive and reflective eye, Sayoh values using her ingenuity to approach and solve issues from every angle.

**Comment by allysonaustin** [comment]
Thanks for submitting!

Speak in first person. It comes across more confident and flows better on a resume/profile to talk as yourself, not about yourself.

I’m a bit confused by the 3rd sentence - what do you mean by “UX Designer collage?” Additionally, this sentence splits the two phrases that discuss ingenuity and imagination, which seem to be more closely connected. It might behoove you to put these ideas together.

I encourage you to read your statement out loud. You have a lot of ideas and elements present in this statement and I think it would benefit you to have a more succinct approach. Reading out loud will help you recognise the elements that are out of place or unnecessary.

Great work! Let me know if you have questions.
A
