### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by ghost** [ga-dc/outcomes#140]

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

Move your skills section just beneath your brand statement and start with your UX and technical skills.
 
Move your education to the bottom. UXDI should be listed as a fully developed entry at the top of your experience section and then as a single-line item in your education section.

In your UXDI experience section, focus on what you accomplished in the course by adding in your individual projects. List the skills you used to build each project.

“Performed” is misspelled in your NatureBridge section.

Beef up your experience sections with more specific details and statistics. They’re looking very sparse at present.

Great work! Let me know if you have questions.
A
