### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by samrijolie** [ga-dc/outcomes#141]

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. You have two education sections. Delete the extra one and move the remaining education entry to the bottom of the resume. 
2. Add your brand statement beneath your header.
3. It seems like your experience sections don't fit in your template - you have a blue line at the bottom that's out of place.  Additionally, your recent additions have a different font than the rest of the resume. Edit to avoid these inconsistencies.
4. Add a section for UXDI and include all of the projects that you created. List yourself a UXDI student.

Let me know if you have questions.
A
