### ISSUE TITLE
Javi Calderon UXDI 15 Resume Draft 

### ISSUE THREAD

**Issue by Calderon00** [ga-dc/outcomes#142]
Adding a new resume including UXDI stuff - not a fan of it so far. Also including my last resume pre-UXDI. 
[Guillermo J Calderon - RESUME.pdf](https://github.com/ga-dc/outcomes/files/1917544/Guillermo.J.Calderon.-.RESUME.pdf)

[Javi Calderon UXDI Resume V1.pdf](https://github.com/ga-dc/outcomes/files/1917546/Javi.Calderon.UXDI.Resume.V1.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. I encourage you to include your email address spelled out. At some point, this will probably be printed and then the link is unhelpful.

2. Your resume needs to be updated for your current career goals. Add in your UX skills to your skills section, and add UXDI to the top of your experience section. As you go through the course, list each project and focus on the skills you've used to create them. 

3. Replace your summary with your brand statement. 

4. Add UXDI as a single-line item only in your education section.

Let me know if you have questions.
A
