### ISSUE TITLE
UXDI15 Sayoh Mansaray Draft Resume

### ISSUE THREAD

**Issue by smansar** [ga-dc/outcomes#144]
[UXDI15 Sayoh Mansaray Draft Resume.pdf](https://github.com/ga-dc/outcomes/files/1925609/UXDI15.Sayoh.Mansaray.Draft.Resume.pdf)

Comments for reviewer: I have more content to add and adjust, including: fixing spacing, editing GA description & fleshing out project bullets to add deliverables, editing and inserting final brand statement, adding a portfolio link, moving the first section under professional experience to a separate/side hustle section since it's unpaid, etc.)

**Comment by allysonaustin** [comment]
Thanks for submitting! You've done a really excellent job with this! I have a few comments for you below.

1. Be cognizant of your tenses. All previous experience should be in the past tense, and anything currently happening should be in present tense.

2. You'll want to include a link to your portfolio - prepare a space for that.

3. Your brand statement is very brief and would benefit from more presence. Continue the statement by explaining to what ends you have these qualities. What is the effect? What problems are you addressing?

4. I encourage you to print your resume and make sure the colors & pattern are dark enough to be readable.

Let me know if you have questions!
A
