### ISSUE TITLE
Carlos Wilkins Brand Statement #UXDI-13

### ISSUE THREAD

**Issue by KingLoSo** [ga-dc/outcomes#74]
I am a Passionate UX Designer inspired by the world. My background in Graphic Design and the arts mixed with my curiosity of the world always leads me to find the spark for great change. Having background as a chef has given me the ability to work as a team player in an extremely stressful situation with a calm head.

**Comment by jschwa1** [comment]
I am a passionate UX designer who finds inspiration in the world around me. With a background in graphic design and a love of the arts, I believe that creativity combined with a dependable, ambitious team can truly affect positive change in the world.
