### ISSUE TITLE
Marquet Reid's Resume

### ISSUE THREAD

**Issue by quetcodesfire** [ga-dc/outcomes#95]
[MarquetReid.pdf](https://github.com/ga-dc/outcomes/files/1598972/MarquetReid.pdf)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. The third sentence of your brand statement doesn't make sense. Read your statement out loud to figure out where it goes amiss and edit. 

2. Remove the scales on your skills sections. If it's listed, it's assumed you're comfortable with that skill.

3. The description in your WDI section doesn't seem to match up with the course. Edit and add your projects. List the skills and technologies used to complete them.

4. Your descriptions could be strengthened with more detail. Focused on what you accomplished in each position and not just what you were responsible for. 

5. Be thoughtful about your coloring. If you need to print your resume, how will this dark background turn out?

Great work!
A
