### ISSUE TITLE
Emily Lawrence draft resume

### ISSUE THREAD

**Issue by lawrenea** [ga-dc/outcomes#98]
[Emily Lawrence resume 2018.docx](https://github.com/ga-dc/outcomes/files/1610293/Emily.Lawrence.resume.2018.docx)

**Comment by allysonaustin** [comment]
Thanks for submitting! 

I've made comments/edits directly on the document attached below. Let me know if you have questions.

Excellent work!
A
[Emily.Lawrence.resume.2018.docx](https://github.com/ga-dc/outcomes/files/1628629/Emily.Lawrence.resume.2018.docx)
