### ISSUE TITLE
Ari Givner's Resume

### ISSUE THREAD

**Issue by agivner** [ga-dc/outcomes#99]
I'm a UX designer and writer looking for ways to use innovative technology to improve the world.

[GA UXDI - Resume.docx](https://github.com/ga-dc/outcomes/files/1610591/GA.UXDI.-.Resume.docx)

**Comment by allysonaustin** [comment]
Thanks for submitting! I have a few edits and suggestions for you below.

1. Your layout is very confusing to me. The sections aren't aligned well, and things seem to be a bit jumbled. Be sure to streamline it for a much stronger, readable resume.

2. No need to include your address in the header - Washington DC is sufficient. Additionally, add your brand statement to the top of your resume beneath your header. It's a very strong introduction to who you are and what you do.

3. You have repeated one of the bullet points in your UXDI section. Be sure to delete it. Also, I encourage you to include your projects in your UX section. List the skills and technologies you used to complete each one.

4. Be more specific in your experience sections. Put together newsletters using what? How many applications did you vet? Giving specific details will make this section much stronger!

Great work! Let me know if you have questions.
A
